# build with Flutter 2.10.5
name: tommypush
description: Simple Push Notifications receiver

version: 23.5.9+5

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9         # toast messages
  firebase_core: ^2.2.0        # push notifications
  firebase_messaging: ^14.1.0  # push notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
