# build with Flutter 3.19.4 (Intel x64), CocoaPods 1.16.2
name: tommypush
description: Simple Push Notifications receiver

version: 24.5.28+7

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.32.0       # push notifications
  firebase_messaging: 14.9.4  # push notifications

dev_dependencies:
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
