# built with Flutter 3.38.5 (Mac Apple M1), Dart 3.10.4, CocoaPods 1.16.2, Xcode 26.2
name: tommypush
description: Simple Push Notifications receiver
version: 1.1.2+10

environment:
  sdk: ">=3.10.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 4.3.0        # push notifications (both needed!)
  firebase_messaging: 16.1.0  # push notifications (both needed!)

flutter:
  uses-material-design: true
